# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a061a5268c086902d9e6cf3549e6d4dfca1b0ace8c393acaf14e9ffa3ab6a9070abae9cdbfcb3d868cb48c416b9e8ba448deaa8e60856202e54c323fb21cfd7

test:
  secret_key_base: 23af1a6aa4dc7fc2a495f606b130f8c8126fdb15f902f042c2d388ae8fe2223f5d81ce54b3e04b1170ef160094f0b7029bd923393f901b20581a276e1245e088

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
